# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, max_length=100, null=True)),
                ('phone_number', models.TextField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('recommended_by', models.ManyToManyField(to='owners.Owner')),
            ],
        ),
    ]
