# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='recommended_by',
            field=models.ManyToManyField(blank=True, to='owners.Owner'),
        ),
    ]
