# Generated by Django 2.0 on 2018-01-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_auto_20171217_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='recommended_by',
        ),
        migrations.AddField(
            model_name='owner',
            name='recommended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.Owner'),
        ),
    ]
