# Generated by Django 2.0 on 2018-01-17 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_salon_photo'),
        ('owners', '0003_auto_20180106_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salons.Salon'),
        ),
    ]
