notifications:
  email: false

sudo: true

language: python

cache:
  - pip

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial

install:
  - travis_retry pip install -r requirements.txt

script:
  - isort -rc -c -df **/*.py
  - pycodestyle --exclude='**/migrations/*' **/*.py

before_install:
  - travis_retry pip install --upgrade pip setuptools py
  - travis_retry pip install twine wheel
