# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
                ('gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')])),
                ('species', models.TextField(default='dog', max_length=50)),
                ('size', models.TextField(blank=True, choices=[('miniature', 'Miniature'), ('medium', 'Medium'), ('large', 'Large'), ('giant', 'Giant')], max_length=20)),
                ('breed', models.TextField(max_length=20)),
                ('color', models.TextField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('motes', models.TextField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.Owner')),
            ],
        ),
    ]
