# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 22:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='size',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='species',
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breeds.Breed'),
        ),
    ]
