# Generated by Django 2.0 on 2018-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20171113_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(default='animal-avatars/None/no-img.png', upload_to='animal-avatars/'),
        ),
    ]
