# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
                ('species', models.TextField(default='dog', max_length=50)),
                ('size', models.TextField(blank=True, choices=[('miniature', 'Miniature'), ('medium', 'Medium'), ('large', 'Large'), ('giant', 'Giant')], max_length=20)),
                ('grooming_notes', models.TextField(blank=True, max_length=50)),
                ('hair_type', models.TextField(blank=True, max_length=50)),
            ],
        ),
    ]
