# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='breed',
            name='weight',
            field=models.IntegerField(default=20),
        ),
    ]
