# Generated by Django 2.0 on 2018-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0002_auto_20171217_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='photo',
            field=models.ImageField(default='breed-avatars/None/no-img.png', upload_to='breed-avatars/'),
        ),
    ]
