# Generated by Django 2.0 on 2018-01-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, max_length=100, null=True)),
                ('phone_number', models.TextField(max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('subscription_type', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
